/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef ADS_CAN_V1_5_H
#define ADS_CAN_V1_5_H

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	uint16_t ADS_AEB_TarAcce; /* scaling 0.0, offset -16.0, units m/s2  */
	uint8_t ADS_TarAcce; /* scaling 0.1, offset -7.0, units m/s2  */
	uint8_t ADS_Mode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_Driveoff_Req; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_DecToStop; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_AEB_TgtDecel_Req; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x111_ADS1_t;

typedef PREPACK struct {
	uint16_t ADS_ReqEPSTargetAngle; /* scaling 0.1, offset -800.0, units deg  */
	uint8_t ADS_EPSMode; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x113_ADS_EPS_t;

typedef PREPACK struct {
	uint8_t ADS_ShiftMode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_TargetGear; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x115_ADS_SHIFTER_t;

typedef PREPACK struct {
	uint16_t SteerWheelAngle; /* scaling 0.1, offset 0.0, units ��  */
	uint16_t SteerWheelSpd; /* scaling 0.1, offset 0.0, units ��/s  */
} POSTPACK can_0x235_FBS4_t;

typedef PREPACK struct {
	uint16_t EngSpd; /* scaling 0.1, offset 0.0, units rpm  */
	uint8_t AccPedalPos; /* scaling 0.4, offset 0.0, units %  */
	uint8_t EPSDrvInputTrqValue; /* scaling 0.2, offset -22.8, units Nm  */
	uint8_t EPSConsumedCurrValue; /* scaling 0.5, offset 0.0, units A  */
	uint8_t EPS_StreeingMode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPSCurrMod; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPBSwtichPosition; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CurrentGear; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x237_FBS3_t;

typedef PREPACK struct {
	uint16_t FRWheelSpd; /* scaling 0.1, offset 0.0, units Km/h  */
	uint16_t RLWheelSpd; /* scaling 0.1, offset 0.0, units Km/h  */
	uint16_t RRWheelSpd; /* scaling 0.1, offset 0.0, units Km/h  */
	uint16_t VehicleSpd; /* scaling 0.1, offset 0.0, units Km/h  */
	uint8_t RLWheelDriveDirection; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RRWheelDirection; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FLWheelDirection; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x240_FBS2_t;

typedef PREPACK struct {
	uint8_t ShiftFail; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPBFail; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EngFail; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ESPFail; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPSFail; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x241_FAIL_t;

typedef PREPACK struct {
	uint16_t LongitudeAcce; /* scaling 0.0, offset -21.6, units m/s^2  */
	uint16_t LateralAcce; /* scaling 0.0, offset -21.6, units m/s^2  */
	uint16_t VehDynYawRate; /* scaling 0.0, offset -2.1, units rad/s  */
	uint16_t FLWheelSpd; /* scaling 0.1, offset 0.0, units Km/h  */
	uint8_t FRWheelDirection; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x243_FBS1_t;

typedef PREPACK struct {
	uint16_t ACC_TARGET_ACCELERATION; /* scaling 0.0, offset -7.2, units none  */
	uint8_t CHECKSUM_ACC1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t UPPER_VALUE_COMFORT_BAND; /* scaling 0.0, offset 0.0, units none  */
	uint8_t LOWER_VALUE_COMFORT_BAND; /* scaling 0.0, offset 0.0, units none  */
	uint8_t MAX_TARGET_ACCELERATION; /* scaling 0.1, offset 0.0, units none  */
	uint8_t MIN_TARGET_ACCELERATION; /* scaling 0.1, offset -12.7, units none  */
	uint8_t ALIVECONTER_ACC1; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ACC_MODE_ESP; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SHUTDOWN_MODE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ACC_WORK_MODE; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BRAKE_PREFERRED; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ACC_MINIMUM_BRAKING; /* scaling 1.0, offset 0.0, units none  */
	uint8_t DRIVE_OFF; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RUQUEST_DECELERATE_TO_STOP; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x263_ACC_COMMAND_FOR_ESP1_t;

typedef PREPACK struct {
	uint8_t BrakePedalStatus; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EngSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LongitudeDrivingMode; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPBSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FrontFogLmpSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BCM_AvailSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VehicleSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RRWheelSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RLWheelSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FLWheelSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VehDynYawRateValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LateralAcceValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LongitudeAccValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t AccePedalOverride; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPBSwtPositionValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CurrentGearValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPSHandsDetnSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ESPBrakeLightSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPSTrqSnsrSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SteerWheelAngleSign; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_HandsDetnStsValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EPS_InterferDetdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t SteerWheelSpdSign; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RRDoorSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t PassengerDoorSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t DriverDoorSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LowBeamSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RearFogLmpSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FRWheelSpdValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RLDoorSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BrakeLmpSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RightTurnLampSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t LeftTurnLampSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HighBeamSts; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x310_STATUS_t;

typedef PREPACK struct {
	uint8_t ADS_BCM_WorkSts; /* scaling 1.0, offset 0.0, units none  */
	uint8_t TurnlLightON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_BCMWorkStsValid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t ADS_ReqControlBCM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HighBeamtON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t DippedBeamON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t EmergencyLightON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FFogLampON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RFogLampON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t BrakeLight; /* scaling 1.0, offset 0.0, units none  */
	uint8_t HornON; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Fwindshieldwiper; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Rwindshieldwiper; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x38e_ADS3_t;

typedef PREPACK struct {
	uint8_t Req_VIN_Signal; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x390_ADS_Req_VIN_t;

typedef PREPACK struct {
	uint8_t VIN07; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN06; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN05; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN04; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN03; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN02; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN01; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN00; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x391_VIN_Resp1_t;

typedef PREPACK struct {
	uint8_t VIN15; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN14; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN13; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN12; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN11; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN10; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN09; /* scaling 1.0, offset 0.0, units none  */
	uint8_t VIN08; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x392_VIN_Resp2_t;

typedef PREPACK struct {
	uint8_t VIN16; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x393_VIN_Resp3_t;

typedef PREPACK struct {
	uint16_t ACC_TARGET_ACCELERATION; /* scaling 0.0, offset -7.2, units none  */
} POSTPACK can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x111_ADS1_time_stamp_rx;
	dbcc_time_stamp_t can_0x113_ADS_EPS_time_stamp_rx;
	dbcc_time_stamp_t can_0x115_ADS_SHIFTER_time_stamp_rx;
	dbcc_time_stamp_t can_0x235_FBS4_time_stamp_rx;
	dbcc_time_stamp_t can_0x237_FBS3_time_stamp_rx;
	dbcc_time_stamp_t can_0x240_FBS2_time_stamp_rx;
	dbcc_time_stamp_t can_0x241_FAIL_time_stamp_rx;
	dbcc_time_stamp_t can_0x243_FBS1_time_stamp_rx;
	dbcc_time_stamp_t can_0x263_ACC_COMMAND_FOR_ESP1_time_stamp_rx;
	dbcc_time_stamp_t can_0x310_STATUS_time_stamp_rx;
	dbcc_time_stamp_t can_0x38e_ADS3_time_stamp_rx;
	dbcc_time_stamp_t can_0x390_ADS_Req_VIN_time_stamp_rx;
	dbcc_time_stamp_t can_0x391_VIN_Resp1_time_stamp_rx;
	dbcc_time_stamp_t can_0x392_VIN_Resp2_time_stamp_rx;
	dbcc_time_stamp_t can_0x393_VIN_Resp3_time_stamp_rx;
	dbcc_time_stamp_t can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_time_stamp_rx;
	unsigned can_0x111_ADS1_status : 2;
	unsigned can_0x111_ADS1_tx : 1;
	unsigned can_0x111_ADS1_rx : 1;
	unsigned can_0x113_ADS_EPS_status : 2;
	unsigned can_0x113_ADS_EPS_tx : 1;
	unsigned can_0x113_ADS_EPS_rx : 1;
	unsigned can_0x115_ADS_SHIFTER_status : 2;
	unsigned can_0x115_ADS_SHIFTER_tx : 1;
	unsigned can_0x115_ADS_SHIFTER_rx : 1;
	unsigned can_0x235_FBS4_status : 2;
	unsigned can_0x235_FBS4_tx : 1;
	unsigned can_0x235_FBS4_rx : 1;
	unsigned can_0x237_FBS3_status : 2;
	unsigned can_0x237_FBS3_tx : 1;
	unsigned can_0x237_FBS3_rx : 1;
	unsigned can_0x240_FBS2_status : 2;
	unsigned can_0x240_FBS2_tx : 1;
	unsigned can_0x240_FBS2_rx : 1;
	unsigned can_0x241_FAIL_status : 2;
	unsigned can_0x241_FAIL_tx : 1;
	unsigned can_0x241_FAIL_rx : 1;
	unsigned can_0x243_FBS1_status : 2;
	unsigned can_0x243_FBS1_tx : 1;
	unsigned can_0x243_FBS1_rx : 1;
	unsigned can_0x263_ACC_COMMAND_FOR_ESP1_status : 2;
	unsigned can_0x263_ACC_COMMAND_FOR_ESP1_tx : 1;
	unsigned can_0x263_ACC_COMMAND_FOR_ESP1_rx : 1;
	unsigned can_0x310_STATUS_status : 2;
	unsigned can_0x310_STATUS_tx : 1;
	unsigned can_0x310_STATUS_rx : 1;
	unsigned can_0x38e_ADS3_status : 2;
	unsigned can_0x38e_ADS3_tx : 1;
	unsigned can_0x38e_ADS3_rx : 1;
	unsigned can_0x390_ADS_Req_VIN_status : 2;
	unsigned can_0x390_ADS_Req_VIN_tx : 1;
	unsigned can_0x390_ADS_Req_VIN_rx : 1;
	unsigned can_0x391_VIN_Resp1_status : 2;
	unsigned can_0x391_VIN_Resp1_tx : 1;
	unsigned can_0x391_VIN_Resp1_rx : 1;
	unsigned can_0x392_VIN_Resp2_status : 2;
	unsigned can_0x392_VIN_Resp2_tx : 1;
	unsigned can_0x392_VIN_Resp2_rx : 1;
	unsigned can_0x393_VIN_Resp3_status : 2;
	unsigned can_0x393_VIN_Resp3_tx : 1;
	unsigned can_0x393_VIN_Resp3_rx : 1;
	unsigned can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_status : 2;
	unsigned can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_tx : 1;
	unsigned can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_rx : 1;
	can_0x111_ADS1_t can_0x111_ADS1;
	can_0x113_ADS_EPS_t can_0x113_ADS_EPS;
	can_0x115_ADS_SHIFTER_t can_0x115_ADS_SHIFTER;
	can_0x235_FBS4_t can_0x235_FBS4;
	can_0x237_FBS3_t can_0x237_FBS3;
	can_0x240_FBS2_t can_0x240_FBS2;
	can_0x241_FAIL_t can_0x241_FAIL;
	can_0x243_FBS1_t can_0x243_FBS1;
	can_0x263_ACC_COMMAND_FOR_ESP1_t can_0x263_ACC_COMMAND_FOR_ESP1;
	can_0x310_STATUS_t can_0x310_STATUS;
	can_0x38e_ADS3_t can_0x38e_ADS3;
	can_0x390_ADS_Req_VIN_t can_0x390_ADS_Req_VIN;
	can_0x391_VIN_Resp1_t can_0x391_VIN_Resp1;
	can_0x392_VIN_Resp2_t can_0x392_VIN_Resp2;
	can_0x393_VIN_Resp3_t can_0x393_VIN_Resp3;
	can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_t can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG;
} POSTPACK can_obj_ads_can_v1_5_h_t;

int unpack_message(can_obj_ads_can_v1_5_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message(can_obj_ads_can_v1_5_h_t *o, const unsigned long id, uint64_t *data);
int print_message(const can_obj_ads_can_v1_5_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x111_ADS1_ADS_AEB_TarAcce_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x111_ADS1_ADS_AEB_TarAcce_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x111_ADS1_ADS_TarAcce_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x111_ADS1_ADS_TarAcce_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x111_ADS1_ADS_Mode_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x111_ADS1_ADS_Mode_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x111_ADS1_ADS_Driveoff_Req_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x111_ADS1_ADS_Driveoff_Req_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x111_ADS1_ADS_DecToStop_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x111_ADS1_ADS_DecToStop_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x111_ADS1_ADS_AEB_TgtDecel_Req_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x111_ADS1_ADS_AEB_TgtDecel_Req_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x113_ADS_EPS_ADS_ReqEPSTargetAngle_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x113_ADS_EPS_ADS_ReqEPSTargetAngle_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x113_ADS_EPS_ADS_EPSMode_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x113_ADS_EPS_ADS_EPSMode_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x115_ADS_SHIFTER_ADS_ShiftMode_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x115_ADS_SHIFTER_ADS_ShiftMode_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x115_ADS_SHIFTER_ADS_TargetGear_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x115_ADS_SHIFTER_ADS_TargetGear_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x235_FBS4_SteerWheelAngle_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x235_FBS4_SteerWheelAngle_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x235_FBS4_SteerWheelSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x235_FBS4_SteerWheelSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);


int decode_can_0x237_FBS3_EngSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x237_FBS3_EngSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x237_FBS3_AccPedalPos_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x237_FBS3_AccPedalPos_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x237_FBS3_EPSDrvInputTrqValue_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x237_FBS3_EPSDrvInputTrqValue_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x237_FBS3_EPSConsumedCurrValue_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x237_FBS3_EPSConsumedCurrValue_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x237_FBS3_EPS_StreeingMode_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x237_FBS3_EPS_StreeingMode_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x237_FBS3_EPSCurrMod_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x237_FBS3_EPSCurrMod_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x237_FBS3_EPBSwtichPosition_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x237_FBS3_EPBSwtichPosition_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x237_FBS3_CurrentGear_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x237_FBS3_CurrentGear_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x240_FBS2_FRWheelSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x240_FBS2_FRWheelSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x240_FBS2_RLWheelSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x240_FBS2_RLWheelSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x240_FBS2_RRWheelSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x240_FBS2_RRWheelSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x240_FBS2_VehicleSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x240_FBS2_VehicleSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x240_FBS2_RLWheelDriveDirection_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x240_FBS2_RLWheelDriveDirection_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x240_FBS2_RRWheelDirection_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x240_FBS2_RRWheelDirection_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x240_FBS2_FLWheelDirection_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x240_FBS2_FLWheelDirection_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x241_FAIL_ShiftFail_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x241_FAIL_ShiftFail_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x241_FAIL_EPBFail_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x241_FAIL_EPBFail_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x241_FAIL_EngFail_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x241_FAIL_EngFail_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x241_FAIL_ESPFail_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x241_FAIL_ESPFail_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x241_FAIL_EPSFail_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x241_FAIL_EPSFail_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x243_FBS1_LongitudeAcce_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x243_FBS1_LongitudeAcce_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x243_FBS1_LateralAcce_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x243_FBS1_LateralAcce_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x243_FBS1_VehDynYawRate_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x243_FBS1_VehDynYawRate_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x243_FBS1_FLWheelSpd_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x243_FBS1_FLWheelSpd_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x243_FBS1_FRWheelDirection_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x243_FBS1_FRWheelDirection_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_TARGET_ACCELERATION_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_TARGET_ACCELERATION_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_CHECKSUM_ACC1_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_CHECKSUM_ACC1_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_UPPER_VALUE_COMFORT_BAND_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_UPPER_VALUE_COMFORT_BAND_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_LOWER_VALUE_COMFORT_BAND_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_LOWER_VALUE_COMFORT_BAND_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_MAX_TARGET_ACCELERATION_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_MAX_TARGET_ACCELERATION_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_MIN_TARGET_ACCELERATION_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_MIN_TARGET_ACCELERATION_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_ALIVECONTER_ACC1_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_ALIVECONTER_ACC1_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_MODE_ESP_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_MODE_ESP_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_SHUTDOWN_MODE_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_SHUTDOWN_MODE_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_WORK_MODE_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_WORK_MODE_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_BRAKE_PREFERRED_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_BRAKE_PREFERRED_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_MINIMUM_BRAKING_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_ACC_MINIMUM_BRAKING_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_DRIVE_OFF_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_DRIVE_OFF_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x263_ACC_COMMAND_FOR_ESP1_RUQUEST_DECELERATE_TO_STOP_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x263_ACC_COMMAND_FOR_ESP1_RUQUEST_DECELERATE_TO_STOP_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x310_STATUS_BrakePedalStatus_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_BrakePedalStatus_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EngSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EngSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_LongitudeDrivingMode_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_LongitudeDrivingMode_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPBSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPBSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_FrontFogLmpSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_FrontFogLmpSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_BCM_AvailSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_BCM_AvailSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_VehicleSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_VehicleSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RRWheelSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RRWheelSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RLWheelSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RLWheelSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_FLWheelSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_FLWheelSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_VehDynYawRateValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_VehDynYawRateValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_LateralAcceValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_LateralAcceValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_LongitudeAccValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_LongitudeAccValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_AccePedalOverride_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_AccePedalOverride_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPBSwtPositionValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPBSwtPositionValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_CurrentGearValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_CurrentGearValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPSHandsDetnSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPSHandsDetnSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_ESPBrakeLightSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_ESPBrakeLightSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPSTrqSnsrSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPSTrqSnsrSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_SteerWheelAngleSign_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_SteerWheelAngleSign_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPS_HandsDetnStsValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPS_HandsDetnStsValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_EPS_InterferDetdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_EPS_InterferDetdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_SteerWheelSpdSign_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_SteerWheelSpdSign_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RRDoorSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RRDoorSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_PassengerDoorSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_PassengerDoorSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_DriverDoorSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_DriverDoorSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_LowBeamSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_LowBeamSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RearFogLmpSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RearFogLmpSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_FRWheelSpdValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_FRWheelSpdValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RLDoorSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RLDoorSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_BrakeLmpSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_BrakeLmpSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_RightTurnLampSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_RightTurnLampSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_LeftTurnLampSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_LeftTurnLampSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x310_STATUS_HighBeamSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x310_STATUS_HighBeamSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x38e_ADS3_ADS_BCM_WorkSts_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_ADS_BCM_WorkSts_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_TurnlLightON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_TurnlLightON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_ADS_BCMWorkStsValid_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_ADS_BCMWorkStsValid_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_ADS_ReqControlBCM_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_ADS_ReqControlBCM_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_HighBeamtON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_HighBeamtON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_DippedBeamON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_DippedBeamON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_EmergencyLightON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_EmergencyLightON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_FFogLampON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_FFogLampON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_RFogLampON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_RFogLampON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_BrakeLight_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_BrakeLight_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_HornON_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_HornON_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_Fwindshieldwiper_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_Fwindshieldwiper_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x38e_ADS3_Rwindshieldwiper_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x38e_ADS3_Rwindshieldwiper_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x390_ADS_Req_VIN_Req_VIN_Signal_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x390_ADS_Req_VIN_Req_VIN_Signal_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x391_VIN_Resp1_VIN07_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN07_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN06_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN06_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN05_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN05_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN04_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN04_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN03_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN03_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN02_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN02_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN01_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN01_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x391_VIN_Resp1_VIN00_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x391_VIN_Resp1_VIN00_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x392_VIN_Resp2_VIN15_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN15_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN14_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN14_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN13_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN13_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN12_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN12_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN11_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN11_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN10_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN10_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN09_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN09_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);
int decode_can_0x392_VIN_Resp2_VIN08_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x392_VIN_Resp2_VIN08_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0x393_VIN_Resp3_VIN16_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, uint8_t *out);
int encode_can_0x393_VIN_Resp3_VIN16_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, uint8_t in);


int decode_can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_ACC_TARGET_ACCELERATION_ads_can_v1_5_h(const can_obj_ads_can_v1_5_h_t *o, double *out);
int encode_can_0xc0000000_VECTOR__INDEPENDENT_SIG_MSG_ACC_TARGET_ACCELERATION_ads_can_v1_5_h(can_obj_ads_can_v1_5_h_t *o, double in);


#ifdef __cplusplus
} 
#endif

#endif
